#!/bin/bash

set -euo pipefail # Set bash options to exit on error, unset variable or failed command in a pipeline

function on_failure {
  echo "The script" "${0##*/}" "has failed" # Print an error message if the script fails
}

trap on_failure ERR # Set a trap to call the on_failure function if an error occurs
source src/getopts # Source the getopts script to parse command line options
APP_PATH=$(pwd -P) # Get the absolute path of the current working directory

if [[ -z "${input:-}" || -z "{$model:-}" ]]
then
  echo "ERROR: Both input (-i) and model (-m) arguments must be provided"
  exit 1
fi

TIMESTAMP=$(date +"%Y-%m-%d_%H.%M.%S") # Get the current date and time in a specific format
OUT_DIR="output/output_$TIMESTAMP" # Set the output directory path
mkdir -p "$OUT_DIR" "$OUT_DIR"/tmp # Create the output and temporary directories

echo ""
echo "Housekeeping complete"
echo ""

# Executing matrix conversion
singularity run \
  --no-home \
  --pwd "$APP_PATH" \
  -B "$APP_PATH":"$APP_PATH" \
  -B "${input}":"${input}" \
  docker://public.ecr.aws/chobiolab/seurat-base:v4-r2 \
  Rscript "$APP_PATH"/src/matrix-convert.R \
  "$APP_PATH"/"$OUT_DIR"/tmp \
  "${input}" 2>&1 \
  | tee -a "$APP_PATH"/"$OUT_DIR"/celltypist-log.txt

echo ""
echo "Counts sparse matrix to expression matrix conversion complete"
echo ""

# Executing celltypist
singularity run \
  -B "$APP_PATH":/data \
  docker://quay.io/teichlab/celltypist:latest \
  celltypist \
  --indata /data/"$OUT_DIR"/tmp/counts.csv \
  --model "${model}".pkl \
  --outdir /data/"$OUT_DIR" \
  --majority-voting 2>&1 \
  | tee -a "$APP_PATH"/"$OUT_DIR"/celltypist-log.txt

echo ""
echo "CellTypist annotation prediction complete"
echo ""

# Executing application of predicted labels back onto input object
singularity run \
  --no-home \
  --pwd "$APP_PATH" \
  -B "$APP_PATH":"$APP_PATH" \
  -B "${input}":"${input}" \
  docker://public.ecr.aws/chobiolab/seurat-base:v4-r2 \
  Rscript "$APP_PATH"/src/apply-ann.R \
  "$APP_PATH"/"$OUT_DIR" \
  "${input}" 2>&1 \
  | tee -a "$APP_PATH"/"$OUT_DIR"/celltypist-log.txt

echo ""
echo "Application of predicted labels back onto input object complete"
echo ""

rm -rf "$OUT_DIR"/tmp # Remove the temporary directory

echo ""
echo "Annotation routine complete"
echo ""
