#!/bin/bash

WORKERS=8
RAM=8

# pass arguments from cli
while getopts i:m:w:r: option
do
    case "${option}"
        in
        i) INPUT=${OPTARG};;
        m) MODEL=${OPTARG};;
        w) WORKERS=${OPTARG};;
        r) RAM=${OPTARG};;
    esac
done

